<a href="https://colab.research.google.com/github/OjureFred/Eduonix-Python-Fundamentals/blob/main/Python_Fundamentals_Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Import data related libraries
import pandas as pd
import numpy as np
import seaborn as sns

#Import GUI Libraries
from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets
from IPython.display import display

In [ ]:
#Load Car Crashes dataset from seaborn and display head information
df_car_crashes = sns.load_dataset("car_crashes")
df_car_crashes.head()

   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
0   18.8     7.332    5.640  ...       784.55      145.08      AL
1   18.1     7.421    4.525  ...      1053.48      133.93      AK
2   18.6     6.510    5.208  ...       899.47      110.35      AZ
3   22.4     4.032    5.824  ...       827.34      142.39      AR
4   12.0     4.200    3.360  ...       878.41      165.63      CA

[5 rows x 8 columns]

In [ ]:
#Statistical measures of crash data
df_car_crashes.describe()

           total   speeding    alcohol  ...  no_previous  ins_premium  ins_losses
count  51.000000  51.000000  51.000000  ...    51.000000    51.000000   51.000000
mean   15.790196   4.998196   4.886784  ...    14.004882   886.957647  134.493137
std     4.122002   2.017747   1.729133  ...     3.764672   178.296285   24.835922
min     5.900000   1.792000   1.593000  ...     5.900000   641.960000   82.750000
25%    12.750000   3.766500   3.894000  ...    11.348000   768.430000  114.645000
50%    15.600000   4.608000   4.554000  ...    13.775000   858.970000  136.050000
75%    18.500000   6.439000   5.604000  ...    16.755000  1007.945000  151.870000
max    23.900000   9.450000  10.038000  ...    21.280000  1301.520000  194.780000

[8 rows x 7 columns]

In [ ]:
#Group By Alcohol and Speeding
df_car_crashes_group = df_car_crashes.groupby(["speeding", "ins_losses"])

for key, item in df_car_crashes_group:
    print(df_car_crashes_group.get_group(key), "\n\n")

    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
30   11.2     1.792    3.136  ...      1301.52      159.85      NJ

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
21    8.2     1.886     2.87  ...      1011.14      135.63      MA

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
27   14.9     1.937    5.215  ...       732.28      114.82      NE

[1 rows x 8 columns]


   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
8    5.9     2.006    1.593  ...      1273.89      136.05      DC

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
23    9.6     2.208    2.784  ...       777.18      133.35      MN

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
46   12.7     2.413    3.429  ...       768.95      153.72      VA

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
24   17.6      2.64    5.456  ...       896.07      155.77      MS

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
15   15.7     2.669    3.925  ...       649.06      114.47      IA

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
10   15.6     2.964      3.9  ...       913.15       142.8      GA

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
22   14.1     3.384    3.948  ...      1110.61      152.26      MI

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
31   18.4     3.496    4.968  ...       869.85      120.75      NM

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
14   14.5     3.625    4.205  ...       710.46      108.92      IN

[1 rows x 8 columns]


   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
9   17.9     3.759    5.191  ...      1160.13      144.18      FL

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
39   11.1     3.774    4.218  ...      1148.99      148.58      RI

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
32   12.3     3.936    3.567  ...      1234.31      150.01      NY

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
35   14.1     3.948    4.794  ...       697.73      133.52      OH

[1 rows x 8 columns]


   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
3   22.4     4.032    5.824  ...       827.34      142.39      AR

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
29   11.6      4.06     3.48  ...       746.54      120.21      NH

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
17   21.4     4.066    4.922  ...       872.51      137.13      KY

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
45   13.6      4.08     4.08  ...        716.2      109.61      VT

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
42   19.5     4.095    5.655  ...       767.91      155.57      TN

[1 rows x 8 columns]


   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
4   12.0       4.2     3.36  ...       878.41      165.63      CA

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
37   12.8     4.224    3.328  ...       804.71      104.61      OR

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
20   12.5      4.25      4.0  ...      1048.78       192.7      MD

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
47   10.6     4.452    3.498  ...       890.03      111.62      WA

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
13   12.8     4.608    4.352  ...       803.11      139.15      IL

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
16   17.8     4.806    4.272  ...       780.45       133.8      KS

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
44   11.3     4.859    1.808  ...       809.38      109.48      UT

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
49   13.8     4.968    4.554  ...       670.31      106.62      WI

[1 rows x 8 columns]


   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
6   10.8     4.968    3.888  ...      1068.73      167.02      CT

[1 rows x 8 columns]


   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
5   13.6     5.032    3.808  ...        835.5      139.91      CO

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
28   14.7     5.439    4.704  ...      1029.87      138.71      NV

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
34   23.9     5.497   10.038  ...       688.75      109.72      ND

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
12   15.3     5.508    4.437  ...       641.96       82.75      ID

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
19   15.1     5.738     4.53  ...       661.88       96.57      ME

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
41   19.4     6.014    6.402  ...       669.31       96.87      SD

[1 rows x 8 columns]


   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
7   16.2     6.156     4.86  ...      1137.87      151.48      DE

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
36   19.9     6.368    5.771  ...       881.51      178.86      OK

[1 rows x 8 columns]


   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
2   18.6      6.51    5.208  ...       899.47      110.35      AZ

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
33   16.8     6.552    5.208  ...       708.24      127.82      NC

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
25   16.1     6.923    5.474  ...       790.32      144.45      MO

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
18   20.5     7.175    6.765  ...      1281.55      194.78      LA

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
50   17.4     7.308    5.568  ...       791.14      122.04      WY

[1 rows x 8 columns]


   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
0   18.8     7.332     5.64  ...       784.55      145.08      AL

[1 rows x 8 columns]


   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
1   18.1     7.421    4.525  ...      1053.48      133.93      AK

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
43   19.4      7.76    7.372  ...      1004.75      156.83      TX

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
48   23.8     8.092    6.664  ...       992.61      152.56      WV

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
26   21.4     8.346    9.416  ...       816.21       85.15      MT

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
40   23.9     9.082    9.799  ...       858.97      116.29      SC

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
38   18.2       9.1    5.642  ...       905.99      153.86      PA

[1 rows x 8 columns]


    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
11   17.5      9.45    7.175  ...       861.18      120.92      HI

[1 rows x 8 columns]

In [ ]:
#create crosstab of data
this = pd.crosstab(columns = df_car_crashes["speeding"], index = [df_car_crashes["alcohol"], df_car_crashes["no_previous"], df_car_crashes["ins_premium"], df_car_crashes["ins_losses"]])

this

speeding                                    1.792  1.886  ...  9.100  9.450
alcohol no_previous ins_premium ins_losses                ...
1.593   5.900       1273.89     136.05          0      0  ...      0      0
1.808   10.848      809.38      109.48          0      0  ...      0      0
2.784   8.448       777.18      133.35          0      0  ...      0      0
2.870   6.560       1011.14     135.63          0      1  ...      0      0
3.136   8.736       1301.52     159.85          1      0  ...      0      0
3.328   11.520      804.71      104.61          0      0  ...      0      0
3.360   10.680      878.41      165.63          0      0  ...      0      0
3.429   11.176      768.95      153.72          0      0  ...      0      0
3.480   9.628       746.54      120.21          0      0  ...      0      0
3.498   9.116       890.03      111.62          0      0  ...      0      0
3.567   9.840       1234.31     150.01          0      0  ...      0      0
3.808   12.920      835.50      139.91          0      0  ...      0      0
3.888   8.856       1068.73     167.02          0      0  ...      0      0
3.900   14.508      913.15      142.80          0      0  ...      0      0
3.925   13.659      649.06      114.47          0      0  ...      0      0
3.948   10.857      1110.61     152.26          0      0  ...      0      0
4.000   12.375      1048.78     192.70          0      0  ...      0      0
4.080   12.920      716.20      109.61          0      0  ...      0      0
4.205   13.775      710.46      108.92          0      0  ...      0      0
4.218   8.769       1148.99     148.58          0      0  ...      0      0
4.272   15.130      780.45      133.80          0      0  ...      0      0
4.352   12.288      803.11      139.15          0      0  ...      0      0
4.437   14.994      641.96      82.75           0      0  ...      0      0
4.525   17.014      1053.48     133.93          0      0  ...      0      0
4.530   12.684      661.88      96.57           0      0  ...      0      0
4.554   11.592      670.31      106.62          0      0  ...      0      0
4.704   14.553      1029.87     138.71          0      0  ...      0      0
4.794   11.562      697.73      133.52          0      0  ...      0      0
4.860   16.038      1137.87     151.48          0      0  ...      0      0
4.922   16.264      872.51      137.13          0      0  ...      0      0
4.968   18.032      869.85      120.75          0      0  ...      0      0
5.191   16.826      1160.13     144.18          0      0  ...      0      0
5.208   13.608      708.24      127.82          0      0  ...      0      0
        17.856      899.47      110.35          0      0  ...      0      0
5.215   13.410      732.28      114.82          0      0  ...      0      0
5.456   17.600      896.07      155.77          0      0  ...      0      0
5.474   13.524      790.32      144.45          0      0  ...      0      0
5.568   15.660      791.14      122.04          0      0  ...      0      0
5.640   15.040      784.55      145.08          0      0  ...      0      0
5.642   16.016      905.99      153.86          0      0  ...      1      0
5.655   15.795      767.91      155.57          0      0  ...      0      0
5.771   18.706      881.51      178.86          0      0  ...      0      0
5.824   21.280      827.34      142.39          0      0  ...      0      0
6.402   16.684      669.31      96.87           0      0  ...      0      0
6.664   20.706      992.61      152.56          0      0  ...      0      0
6.765   20.090      1281.55     194.78          0      0  ...      0      0
7.175   15.225      861.18      120.92          0      0  ...      0      1
7.372   16.878      1004.75     156.83          0      0  ...      0      0
9.416   18.190      816.21      85.15           0      0  ...      0      0
9.799   19.359      858.97      116.29          0      0  ...      0      0
10.038  20.554      688.75      109.72          0      0  ...      0      0

[51 rows x 50 columns]

In [ ]:
#Create widgets to make the data stylish
#1. Sort Car crashes by state

ALL = "ALL"
def unique_crash_values_ALL(array):
  unique = array.unique().tolist()
  unique.sort()
  unique.insert(0, ALL)
  return unique

In [ ]:
#Create Dropdown to select state values
drop_downState = widgets.Dropdown(options = unique_crash_values_ALL(df_car_crashes.abbrev))

In [ ]:
def dropdown_state_handler(change):
  if(change.new == ALL):
    display(df_car_crashes)
  else:
    display(df_car_crashes[df_car_crashes.abbrev == change.new])

In [ ]:
drop_downState.observe(dropdown_state_handler,  names = "value")

In [ ]:
drop_downState

Dropdown(options=('ALL', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', '…

   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
3   22.4     4.032    5.824  ...       827.34      142.39      AR

[1 rows x 8 columns]

   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
4   12.0       4.2     3.36  ...       878.41      165.63      CA

[1 rows x 8 columns]

   total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
8    5.9     2.006    1.593  ...      1273.89      136.05      DC

[1 rows x 8 columns]